### ISSUE TITLE
Unknown custom element: <tree-view> 

### ISSUE THREAD

**Issue by eddyekofo94** [arvidkahl/vue-json-tree-view#9]
Thank you for suh a great library, but I followed the steps yet I still recieve this error, any help?

`Unknown custom element: <tree-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
`
Thank you in advance :+1:

**Comment by arvidkahl** [comment]
Can you provide some sample code? Maybe in a jsfiddle? Did you import the component correctly? Is it installed via npm?

**Comment by carlosvega** [comment]
I've started to have this issue when I upgraded from 2.1.4 to 2.1.6.
In fact, I didn't upgrade, but since my package.json has "^2.1.4" it will use any compatible version. Apparently, 2.1.6 is not compatible.

This is what I get. I can confirm it also happens if I use 2.1.5.

Everything with Vue.js v2.6.10

> [Vue warn]: Unknown custom element: <tree-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by eddyekofo94** [comment]
Haven't looked into this library in years. Don't even know how I could help

**Comment by carlosvega** [comment]
Oh no, I was just re-using the same ticket you created years ago. There are some recent releases that seem to break something. Maybe @arvidkahl will consider to re-open the ticket.
